### ISSUE TITLE
Crash when starting server: attempt to call field '_season_transition_fn' (a nil value)

### ISSUE THREAD

**Issue by worldsayshi** [rezecib/Combined-Status#21]
I get the following error when trying to start a game with this mod (manually and partially copied trace):
attempt to call field '_season_transition_fn' (a nil value)
seasonclock.lua:300 in (method) GetSeasonLengths (Lua)
...
modmain.lua:254 in (upvalue) postfn (Lua)

**Comment by worldsayshi** [comment]
I tried to look over the problematic code for a bit but from my non-existing Lua experience I can't see what is wrong. 

My two cents:
So self._season_transition_fn is nil when running GetSeasonLengths. _season_transition_fn is set in the constructor. There is only one use of the constructor that I can see. In modmain.lua where FindSeasonTransitions seems to be sent in as the _season_transition_fn argument.

Weak hypothesis:
FindSeasonTransitions is declared local. Is this a problem when passing it into another class?

**Comment by worldsayshi** [comment]
Ah! 

I had both the client and server mod enabled. Now that I disabled the client mod it worked. :)

**Comment by rezecib** [comment]
Ah, glad you got it sorted out. The line numbers look a little off, so I'm guessing there were different versions between the two?

It's not obvious to me how self._season_transition_fn would become nil just by running the code twice.
