### ISSUE TITLE
[DST Feature Request?] Mod integration for naughtiness

### ISSUE THREAD

**Issue by penguin0616** [rezecib/Combined-Status#26]
Hi, so I have a DST mod that, among many other things, sends naughtiness information over to clients. If I made a pull request with a modified Combined Status supporting the display of that naughtiness information (just like it does in DS), would that be fine with you?

**Comment by rezecib** [comment]
Yeah, that would be awesome! People file that as a bug/request all the time, and it's frustrated me that with a client mod I have no way to implement it.

**Comment by penguin0616** [comment]
Here's the pull request! #27
Feel free to look it over in case you need me to change something (had to tweak your naughtiness badge a bit). 
Edit: In case you're curious, here's the mod in question responsible for providing the naughtiness information: https://github.com/penguin0616/Insight

**Comment by rezecib** [comment]
fixed in ff2dac3d0cdcb39758190af0e2517b69c2441d3e

Thanks!
