### ISSUE TITLE
Cant connect to server with this mod.

### ISSUE THREAD

**Issue by 666ZTA666** [rezecib/Combined-Status#35]
WARNING!
((string "…/mods/workshop-632083515/modmain.lua"]:548: attempt to call upvalue "Old On Moon Phase Changed' (a nil value)
LUA ERROR stack traceback:
…/./mods/workshop-632083515/modmain.lua:548 in (method) On Moon Phase Changed (Lua) < 544-552 >
…/./mods/workshop-632083515/modmain.lua:499 in (method) On Phase Changed (Lua) < 496-539 >
scripts/widgets/ui clock.lua:126 in (local) fu (Lua) < 126-126 >
scripts/entityscript.lua:1142 in (method) PushEvent (Lua) <1129-1156>
scripts/components/clock.lua:396 in (method) OnUpdate (Lua) < 322-440 >
scripts/update.lua:256 in () ? (Lua) < 218-292 >
This error may have occurred due to a mod you have enabled!
You have the following mods enabled:
"Combined Status"

Rev. 510124 WiN32 SteAM

As far as I could take a log of error. I think that problem in file "modmain.lua" about 1030 lines. Fix it please, your mod is very cool, and it work on my gf comp, but i cant use it.

**Comment by rezecib** [comment]
That trace is from an [unofficial copy of this mod that I don't control](https://steamcommunity.com/sharedfiles/filedetails/?id=632083515). If you use [this one](https://steamcommunity.com/sharedfiles/filedetails/?id=376333686) instead, hopefully that should work for you? Let me know if you still get an error with that.
